version: 2.0.{build}
clone_folder: c:\utfUnknown
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
deploy: off
init:
- git config --global core.autocrlf true
build_script:
- ps: dotnet build -c Release 
test_script:
- ps: cd .\tests\
- ps: dotnet test
- ps: cd ..
after_build:
- ps: cd .\src\
- ps: dotnet pack -c Release 
- ps: cd ..
- ps: Get-ChildItem '**\test-diag.log' | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
- path: '**\test-diag.log'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: 2.0.0.0
  file_version: '{build}'
  informational_version: '{version}'
