version: 1.0.{build}
clone_folder: c:\utfUnknown
image: Visual Studio 2017
before_build:
  - ps: msbuild /t:restore
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy: off
test_script:
  - ps: cd .\tests\
  - ps: dotnet xunit
  - ps: cd ..